# fullsend organization configuration
# https://github.com/fullsend-ai/fullsend
#
# This file is managed by fullsend. Manual edits may be overwritten.
version: "1"
dispatch:
    platform: github-actions
    mode: oidc-mint
inference:
    provider: vertex
defaults:
    roles:
        - fullsend
        - triage
        - coder
        - review
        - retro
        - prioritize
        - qualityflow
    runtime: claude
    max_implementation_retries: 2
    auto_merge: false
repos:
    .fullsend:
        enabled: false
    agents:
        enabled: true
    experiments:
        enabled: true
    fullsend:
        enabled: true
    metrics:
        enabled: true
allowed_remote_resources:
    - https://raw.githubusercontent.com/fullsend-ai/fullsend/
    - https://raw.githubusercontent.com/fullsend-ai/agents/
    - https://raw.githubusercontent.com/redhat-community-ai-tools/qualityflow-fullsend/
create_issues:
    allow_targets:
        orgs:
            - fullsend-ai
        repos:
            - fullsend-ai/fullsend
agents:
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/937a16b672ac0b535660b358f89e2538afc0bf4b/harness/triage.yaml#sha256=f56cbb0a3c1cb71563aa1b2fb80ca9ecb922e4c832f886e8154e2e9beb6b56c6
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/937a16b672ac0b535660b358f89e2538afc0bf4b/harness/code.yaml#sha256=4e52817c68c57d3938fc80a5fb5cd91e6ecad2d5e7a0f51e604d7c07d5f79026
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/937a16b672ac0b535660b358f89e2538afc0bf4b/harness/fix.yaml#sha256=5af5a1658ea36dd0982a475b08e51246224a52a3cdcfd805e837a16a286b6756
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/937a16b672ac0b535660b358f89e2538afc0bf4b/harness/review.yaml#sha256=6b5cd38510ffe0526c46d8172371e9602634254841abe3e8a8e0ce183d9ef7b9
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/937a16b672ac0b535660b358f89e2538afc0bf4b/harness/retro.yaml#sha256=8be74d42aa94ed0083fd1a915f9903435d797b801b3866acd7e8249830388835
  - source: https://raw.githubusercontent.com/fullsend-ai/agents/937a16b672ac0b535660b358f89e2538afc0bf4b/harness/prioritize.yaml#sha256=21cf62dce54fce3ae23cf5e3dfe901d03b69bc5e91533288ffa772187b24e95d
  - source: https://raw.githubusercontent.com/redhat-community-ai-tools/qualityflow-fullsend/b26c947e95e6325284c5542d466a2a016f6aa312/harness/qualityflow.yaml#sha256=473d44a73c465b318fa3cd8dfee2c55b4a5dc7439f994607eb774825c43c17c2
